//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataHandeler
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WinheProjectEntities : DbContext
    {
        public WinheProjectEntities()
            : base("name=WinheProjectEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CustomersDetail> CustomersDetails { get; set; }
        public virtual DbSet<InvoiceHeaderDetail> InvoiceHeaderDetails { get; set; }
        public virtual DbSet<InvoiceLineDetail> InvoiceLineDetails { get; set; }
        public virtual DbSet<ProductDetail> ProductDetails { get; set; }
    }
}
